# User.create!(name:  "管理者1",
#              email: "admin@example.jp",
#              password:  "61346134",
#              password_confirmation: "61346134",
#              admin: true)
# User.create!(name:  "管理者2",
#              email: "admin2@example.jp",
#              password:  "61346134",
#              password_confirmation: "61346134",
#              admin: true)
# User.create!(name:  "管理者3",
#              email: "admin3@example.jp",
#              password:  "61346134",
#              password_confirmation: "61346134",
#              admin: true)
#


Drink.create!(name: "生ビール",price:"480" )
Drink.create!(name: "樽生スパークリングワイン ポールスター",price:"480" )
Drink.create!(name: "ハイボール",price:"400" )
Drink.create!(name: "マカハイボール",price:"500" )
Drink.create!(name: "コークハイボール",price:"480" )
Drink.create!(name: "ガリハイボール",price:"450" )
Drink.create!(name: "竹鶴ハイボール",price:"500" )
Drink.create!(name: "山崎ハイボール",price:"750" )
Drink.create!(name: "山崎12年",price:"1200" )
Drink.create!(name: "獺祭ハイボール",price:"700" )
Drink.create!(name: "田酒ハイボール",price:"800" )
Drink.create!(name: "十四代ハイボール",price:"900" )
Drink.create!(name: "チューハイ",price:"350" )
Drink.create!(name: "緑茶ハイ",price:"380" )
Drink.create!(name: "ウーロンハイ",price:"380" )
Drink.create!(name: "黒ウーロンハイ",price:"500" )
Drink.create!(name: "マカサワー",price:"500" )
Drink.create!(name: "生レモンサワー",price:"450" )
Drink.create!(name: "梅干サワー",price:"450" )
Drink.create!(name: "超梅干サワー",price:"480" )
Drink.create!(name: "カルピスサワー",price:"450" )
Drink.create!(name: "ガリサワー",price:"400" )
Drink.create!(name: "超マカサワー",price:"700" )


SideMenu.create!(name: "焼き鳥を美味しく食べる為のカクテルサラダ",price:"500", picture:"",  comment:"京都坂ノ途中監修,無農薬オーガニック野菜使用")
SideMenu.create!(name: "白レバーのタタキ",price:"500", picture:"", comment:"")
SideMenu.create!(name: "鳥皮ポン酢",price:"400", picture:"", comment:"")
SideMenu.create!(name: "とりわさ",price:"500", picture:"", comment:"")
SideMenu.create!(name: "枝豆ガーリック",price:"400", picture:"", comment:"")
SideMenu.create!(name: "鳥のいくら",price:"400", picture:"", comment:"")
SideMenu.create!(name: "みそきゅうり",price:"350", picture:"", comment:"")
SideMenu.create!(name: "焼き野菜串（A）",price:"150", picture:"", comment:"")
SideMenu.create!(name: "焼き野菜串（B）",price:"200", picture:"", comment:"")
SideMenu.create!(name: "焼き野菜串（C）",price:"300", picture:"", comment:"")
SideMenu.create!(name: "奥久慈卵のこだわりTKG",price:"450", picture:"", comment:"")
SideMenu.create!(name: "鶏スープ茶づけ",price:"500", picture:"", comment:"")
SideMenu.create!(name: "そぼろご飯",price:"600", picture:"", comment:"")
SideMenu.create!(name: "鳥いくら丼",price:"500", picture:"", comment:"")
SideMenu.create!(name: "鶏スープ",price:"200", picture:"", comment:"")


Food.create!(name: "ねぎま",price:"400", picture:"", comment:"")
Food.create!(name: "おび",price:"400", picture:"", comment:"")
Food.create!(name: "そりれす",price:"400", picture:"", comment:"")
Food.create!(name: "アキレス",price:"400", picture:"", comment:"")
Food.create!(name: "もも",price:"400", picture:"", comment:"")
Food.create!(name: "ハラミ",price:"400", picture:"", comment:"")
Food.create!(name: "ハツ",price:"400", picture:"", comment:"")
Food.create!(name: "ハツ落ち",price:"400", picture:"", comment:"")
Food.create!(name: "親ハツ",price:"400", picture:"", comment:"")
Food.create!(name: "白肝",price:"400", picture:"", comment:"")
Food.create!(name: "肝",price:"400", picture:"", comment:"")
Food.create!(name: "黄肝",price:"400", picture:"", comment:"")
Food.create!(name: "親レバー",price:"400", picture:"", comment:"")
Food.create!(name: "網レバー",price:"400", picture:"", comment:"")
Food.create!(name: "砂肝",price:"400", picture:"", comment:"")
Food.create!(name: "えんがわ",price:"400", picture:"", comment:"")
Food.create!(name: "リンパ",price:"400", picture:"", comment:"")
Food.create!(name: "ちょうちん",price:"400", picture:"", comment:"")
Food.create!(name: "金玉",price:"400", picture:"", comment:"")
Food.create!(name: "むね",price:"400", picture:"", comment:"")
Food.create!(name: "ささみ",price:"400", picture:"", comment:"")
Food.create!(name: "ふりそで",price:"400", picture:"", comment:"")
Food.create!(name: "せせり",price:"400", picture:"", comment:"")
Food.create!(name: "皮",price:"400", picture:"", comment:"")
Food.create!(name: "上皮",price:"400", picture:"", comment:"")
Food.create!(name: "ぺた",price:"400", picture:"", comment:"")
Food.create!(name: "ヤゲン",price:"400", picture:"", comment:"")
Food.create!(name: "ヒザ",price:"400", picture:"", comment:"")
Food.create!(name: "かかとおとし",price:"400", picture:"", comment:"")
Food.create!(name: "くびれ",price:"400", picture:"", comment:"")
Food.create!(name: "手羽",price:"400", picture:"", comment:"")
Food.create!(name: "親鶏",price:"400", picture:"", comment:"")
Food.create!(name: "ボンジリ",price:"400", picture:"", comment:"")
Food.create!(name: "油つぼ",price:"400", picture:"", comment:"")
Food.create!(name: "とさか",price:"400", picture:"", comment:"")
Food.create!(name: "白子",price:"400", picture:"", comment:"")
Food.create!(name: "つくね",price:"400", picture:"", comment:"")
Food.create!(name: "玉つくね",price:"400", picture:"", comment:"")
Food.create!(name: "背肝",price:"400", picture:"", comment:"")
Food.create!(name: "あずき",price:"400", picture:"", comment:"")
Food.create!(name: "フア",price:"400", picture:"", comment:"")
Food.create!(name: "ふくらはぎ",price:"400", picture:"", comment:"")
Food.create!(name: "かもねぎ",price:"400", picture:"", comment:"")
